In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

In [8]:
# Conexión 
load_dotenv()
engine = create_engine(f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}")

# 2. Función para leer archivo .sql y devolver un DataFrame
def ejecutar_query_desde_archivo(ruta_archivo):
    with open(ruta_archivo, 'r', encoding='utf-8') as archivo:
        query_sql = archivo.read()
    
    with engine.connect() as conexion:
        # read_sql ejecuta la consulta y arma el DataFrame
        df = pd.read_sql(text(query_sql), con=conexion)
    return df

df_facturacion = ejecutar_query_desde_archivo('queries/01_facturacion_mensual.sql')

# Ver el resultado intermedio
df_facturacion.head()

  mes_venta  total_vendido
0   2016-09         136.23
1   2016-10       51657.53
2   2016-12          19.62
3   2017-01      137006.76
4   2017-02      283621.94

In [6]:
df_gasto = ejecutar_query_desde_archivo('queries/02_gasto_promedio.sql')

df_gasto

   gasto_promedio_por_compra
0                 160.990267

In [9]:
df_metodo_cuotas = ejecutar_query_desde_archivo('queries/03_metodo_cuotas.sql')

df_metodo_cuotas

  metodo_de_pago  cantidad_transacciones  promedio_cuotas
0    credit_card                   76795              3.5
1         boleto                   19784              1.0
2        voucher                    5775              1.0
3     debit_card                    1529              1.0
4    not_defined                       3              1.0

In [10]:
df_estados_mas_facturan = ejecutar_query_desde_archivo('queries/04_estados_mas_facturan.sql')

df_estados_mas_facturan

  estado  total_facturado
0     SP       5998226.96
1     RJ       2144379.69
2     MG       1872257.26
3     RS        890898.54
4     PR        811156.38

In [11]:
df_estados_menos_facturan = ejecutar_query_desde_archivo('queries/05_estados_menos_facturan.sql')

df_estados_menos_facturan

  estado  total_facturado
0     RR         10064.62
1     AP         16262.80
2     AC         19680.62
3     AM         27966.93
4     RO         60866.20