In [13]:
import os
import pandas as pd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

In [14]:
# Conexión 
load_dotenv()
engine = create_engine(f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}")

# 2. Función para leer archivo .sql y devolver un DataFrame
def ejecutar_query_desde_archivo(ruta_archivo):
    with open(ruta_archivo, 'r', encoding='utf-8') as archivo:
        query_sql = archivo.read()
    
    with engine.connect() as conexion:
        # read_sql ejecuta la consulta y arma el DataFrame
        df = pd.read_sql(text(query_sql), con=conexion)
    return df

df_facturacion = ejecutar_query_desde_archivo('queries/01_facturacion_mensual.sql')

# Ver el resultado intermedio
df_facturacion.head()

  mes_venta  total_vendido
0   2016-09         136.23
1   2016-10       51657.53
2   2016-12          19.62
3   2017-01      137006.76
4   2017-02      283621.94

In [15]:
df_gasto = ejecutar_query_desde_archivo('queries/02_gasto_promedio.sql')

df_gasto

   gasto_promedio_por_compra
0                 160.990267

In [16]:
df_metodo_cuotas = ejecutar_query_desde_archivo('queries/03_metodo_cuotas.sql')

df_metodo_cuotas

  metodo_de_pago  cantidad_transacciones  promedio_cuotas
0    credit_card                   76795              3.5
1         boleto                   19784              1.0
2        voucher                    5775              1.0
3     debit_card                    1529              1.0
4    not_defined                       3              1.0

In [17]:
df_estados_mas_facturan = ejecutar_query_desde_archivo('queries/04_estados_mas_facturan.sql')

df_estados_mas_facturan

  estado  total_facturado
0     SP       5998226.96
1     RJ       2144379.69
2     MG       1872257.26
3     RS        890898.54
4     PR        811156.38

In [18]:
df_estados_menos_facturan = ejecutar_query_desde_archivo('queries/05_estados_menos_facturan.sql')

df_estados_menos_facturan

  estado  total_facturado
0     RR         10064.62
1     AP         16262.80
2     AC         19680.62
3     AM         27966.93
4     RO         60866.20

In [19]:
df_categorias_mas_ingresos = ejecutar_query_desde_archivo('queries/06_categorias_mas_ingresos.sql')

df_categorias_mas_ingresos

               categoria  total_ingresos_generados
0          health_beauty                1258681.34
1          watches_gifts                1205005.68
2         bed_bath_table                1036988.68
3         sports_leisure                 988048.97
4  computers_accessories                 911954.32
5        furniture_decor                 729762.49
6             cool_stuff                 635290.85
7             housewares                 632248.66
8                   auto                 592720.11
9           garden_tools                 485256.46

In [20]:
df_categorias_mas_vendidas = ejecutar_query_desde_archivo('queries/07_categorias_mas_vendidas.sql')

df_categorias_mas_vendidas

               categoria  unidades_vendidas
0         bed_bath_table              11115
1          health_beauty               9670
2         sports_leisure               8641
3        furniture_decor               8334
4  computers_accessories               7827
5             housewares               6964
6          watches_gifts               5991
7              telephony               4545
8           garden_tools               4347
9                   auto               4235

In [21]:
df_logistica_tiempos_estados = ejecutar_query_desde_archivo('queries/08_logistica_tiempos_estados.sql')

df_logistica_tiempos_estados

   estado  promedio_dias_retraso  maximo_retraso_historico_dias
0      AL                   -8.7                             50
1      MA                   -9.6                            134
2      SE                  -10.0                            166
3      ES                  -10.5                            181
4      CE                  -10.8                            132
5      BA                  -10.8                            138
6      SP                  -11.1                            175
7      MS                  -11.1                             29
8      PI                  -11.3                            161
9      SC                  -11.5                             69
10     RJ                  -11.8                            188
11     DF                  -12.0                             36
12     TO                  -12.1                             32
13     GO                  -12.2                            152
14     MG                  -13.2                            162
15     PB                  -13.3                             65
16     PR                  -13.3                             73
17     PE                  -13.3                            123
18     RN                  -13.6                            137
19     RS                  -13.9                            155
20     PA                  -14.1                            165
21     MT                  -14.4                             46
22     RR                  -17.3                            132
23     AM                  -19.6                            104
24     AP                  -19.7                            144
25     RO                  -20.1                             15
26     AC                  -20.7                             31

In [ ]:
df_rfm = ejecutar_query_desde_archivo('queries/10_rfm.sql')

df_rfm